CREATE TABLE IF NOT EXISTS cliniques (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL,
    NEQ VARCHAR(25),
    address_ID INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (address_ID) REFERENCES addresses(ID) ON DELETE NO ACTION
);