CREATE TABLE IF NOT EXISTS examens (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    RX_objective VARCHAR(50) NOT NULL,
    RX_subjective VARCHAR(50) NOT NULL,
    acuite INTEGER NOT NULL,
    adjustment VARCHAR(50) NOT NULL,
    lens_type VARCHAR(50) NOT NULL,
    patient_ID INTEGER NOT NULL,
    optometriste_ID INTEGER NOT NULL REFERENCES optometristes(ID) ON DELETE NO ACTION,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (patient_ID) REFERENCES patients(ID) ON DELETE NO ACTION,
    FOREIGN KEY (optometriste_ID) REFERENCES optometristes(ID) ON DELETE NO ACTION
);