CREATE TABLE IF NOT EXISTS examens (
    ID SERIAL PRIMARY KEY,
    RX_objective VARCHAR(50) NOT NULL,
    RX_subjective VARCHAR(50) NOT NULL,
    acuite INTEGER NOT NULL,
    adjustment VARCHAR(50) NOT NULL,
    lens_type VARCHAR(50) NOT NULL,
    patient_ID INTEGER NOT NULL  REFERENCES patients(ID) ON DELETE NO ACTION,
    optometriste_ID INTEGER NOT NULL REFERENCES optometristes(ID) ON DELETE NO ACTION,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);