CREATE TABLE patients_cliniques (
    ID_patients INTEGER REFERENCES patients(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    ID_cliniques INTEGER REFERENCES cliniques(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);