CREATE TABLE IF NOT EXISTS prescriptions (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    periode_validite INTEGER NOT NULL,
    puissance JSON NOT NULL,
    optometriste_ID INTEGER NOT NULL,
    examen_ID INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (optometriste_ID) REFERENCES optometristes(ID) ON DELETE NO ACTION
);