CREATE TABLE IF NOT EXISTS patients_cliniques (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    patient_ID INT REFERENCES patients(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    clinique_ID INT REFERENCES cliniques(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (patient_ID) REFERENCES patients(ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (clinique_ID) REFERENCES cliniques(ID) ON UPDATE CASCADE ON DELETE CASCADE
);