CREATE TABLE IF NOT EXISTS rendezvous (
    patient_ID INTEGER PRIMARY KEY,
    date_rendezvous DATE PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(patient_ID) REFERENCES patients(ID) ON UPDATE CASCADE ON DELETE CASCADE
);